AWSTemplateFormatVersion: "2010-09-09"
Description: Pacu Infrastructure
Resources:
  VulnerableSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "AllowTheWorld"
      GroupDescription: "Allows in everything from everyone"
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: "name"
          Value: "Allow the world"
        -
          Key: "creator"
          Value: "CloudFormation"
  VulnerableUbuntuInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0653e888ec96eab9b"
      InstanceType: "t2.micro"
      SecurityGroups:
        - !Ref VulnerableSecurityGroup
      Tags:
        -
          Key: "name"
          Value: "Vulnerable Ubuntu"
        -
          Key: "creator"
          Value: "CloudFormation"
  VulnerableAmazonLinux:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-02e680c4540db351e"
      InstanceType: "t2.micro"
      SecurityGroups:
        - !Ref VulnerableSecurityGroup
      Tags:
        -
          Key: "name"
          Value: "Vulnerable Amazon Linux"
        -
          Key: "creator"
          Value: "CloudFormation"
